const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,PUB=path.join(ROOT,'public'),DATA=path.join(ROOT,'data'),UP=path.join(ROOT,'uploads'),DB=path.join(DATA,'db.json');[PUB,DATA,UP].forEach(x=>fs.mkdirSync(x,{recursive:true}));
const seed={config:{activityName:'廿载同心·青春同行｜健康三餐打卡',startDate:'2026-09-12',endDate:'2026-09-30',slots:[{id:'breakfast',label:'早餐',start:'06:50',end:'10:00'},{id:'lunch',label:'午餐',start:'10:30',end:'14:00'},{id:'dinner',label:'晚餐',start:'16:30',end:'19:30'}]},users:[{id:'admin',studentId:'admin',name:'管理员',password:'change-me-now',role:'admin'}],checkins:[]};
const get=()=>{if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed,null,2));return JSON.parse(fs.readFileSync(DB))},put=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2)),out=(r,c,x)=>{r.writeHead(c,{'Content-Type':'application/json;charset=utf-8'});r.end(JSON.stringify(x))},read=r=>new Promise((ok,bad)=>{let x='';r.on('data',c=>{x+=c;if(x.length>25e6)bad(Error('单次上传最多25MB'))});r.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch{bad(Error('请求格式错误'))}})});
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date()),time=()=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
const auth=(r,d)=>{try{return d.users.find(u=>u.id===JSON.parse(Buffer.from((r.headers.authorization||'').replace('Bearer ',''),'base64url')).id)}catch{return null}},tok=u=>Buffer.from(JSON.stringify({id:u.id})).toString('base64url');
function image(v,pre){if(!v?.startsWith('data:image/'))return null;let[m,b]=v.split(','),e=(m.match(/data:image\/(png|jpeg|jpg|webp)/)||[])[1]||'jpg',n=`${pre}-${crypto.randomUUID()}.${e==='jpeg'?'jpg':e}`;fs.writeFileSync(path.join(UP,n),Buffer.from(b,'base64'));return'/uploads/'+n}
async function api(q,r,u){let d=get(),p=u.pathname;if(p==='/api/login'&&q.method==='POST'){let b=await read(q),x=d.users.find(z=>z.studentId===b.studentId.trim()&&z.password===b.password);return x?out(r,200,{token:tok(x),user:x,config:d.config}):out(r,401,{error:'学号或密码不正确'})}let me=auth(q,d);if(!me)return out(r,401,{error:'请先登录'});if(p==='/api/me')return out(r,200,{user:me,config:d.config,date:day(),time:time()});
if(p==='/api/checkins'&&q.method==='GET'){let dt=u.searchParams.get('date')||day();return out(r,200,{checkins:d.checkins.filter(x=>x.userId===me.id&&x.date===dt)})}if(p==='/api/checkins'&&q.method==='POST'){if(me.role!=='student')return out(r,403,{error:'管理员账号不可打卡'});let b=await read(q),s=d.config.slots.find(x=>x.id===b.slotId);if(!s)return out(r,400,{error:'打卡时段不存在'});if((b.date||day())!==day())return out(r,400,{error:'只能提交当天材料'});if(time()<s.start||time()>s.end)return out(r,400,{error:`当前不在${s.label}时段（${s.start}–${s.end}）`});let photos=(b.photos||[]).map((x,i)=>image(x,`${me.studentId}-${day()}-${s.id}-${i}`)).filter(Boolean);if(!photos.length)return out(r,400,{error:'至少上传一张水印截图'});d.checkins=d.checkins.filter(x=>!(x.userId===me.id&&x.date===day()&&x.slotId===s.id));d.checkins.push({id:crypto.randomUUID(),userId:me.id,date:day(),slotId:s.id,photos,summary:image(b.summary,`${me.studentId}-${day()}-summary`),note:(b.note||'').slice(0,300),submittedAt:new Date().toISOString(),status:'pending'});put(d);return out(r,201,{ok:true})}
if(me.role!=='admin')return out(r,403,{error:'仅管理员可访问'});if(p==='/api/admin/dashboard'){let dt=u.searchParams.get('date')||day(),ss=d.users.filter(x=>x.role==='student');return out(r,200,{date:dt,config:d.config,students:ss.map(x=>({...x,slots:d.config.slots.map(s=>d.checkins.find(c=>c.userId===x.id&&c.date===dt&&c.slotId===s.id)||null)}))})}if(p==='/api/admin/users'&&q.method==='GET')return out(r,200,{users:d.users.filter(x=>x.role==='student')});if(p==='/api/admin/users'&&q.method==='POST'){let b=await read(q);if(!b.studentId||!b.name||!b.password)return out(r,400,{error:'请填写姓名、学号、初始密码'});if(d.users.some(x=>x.studentId===b.studentId))return out(r,409,{error:'学号已存在'});d.users.push({id:crypto.randomUUID(),studentId:b.studentId,name:b.name,password:b.password,campus:b.campus||'',role:'student'});put(d);return out(r,201,{ok:true})}if(p==='/api/admin/config'&&q.method==='PUT'){d.config={...d.config,...await read(q)};put(d);return out(r,200,{ok:true})}if(p.startsWith('/api/admin/checkins/')&&q.method==='PUT'){let c=d.checkins.find(x=>x.id===p.split('/').pop()),b=await read(q);if(!c)return out(r,404,{error:'记录不存在'});c.status=b.status==='approved'?'approved':'rejected';put(d);return out(r,200,{ok:true})}out(r,404,{error:'接口不存在'})}
http.createServer(async(q,r)=>{let u=new URL(q.url,`http://${q.headers.host}`);try{if(u.pathname.startsWith('/api/'))return await api(q,r,u);let isUp=u.pathname.startsWith('/uploads/'),f=path.join(isUp?UP:PUB,isUp?u.pathname.slice(9):(u.pathname==='/'?'index.html':u.pathname));if(!fs.existsSync(f)){r.writeHead(404);return r.end('Not found')}let types={'.html':'text/html;charset=utf-8','.js':'application/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};r.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(r)}catch(e){out(r,400,{error:e.message})}}).listen(process.env.PORT||3000,()=>console.log('http://localhost:'+(process.env.PORT||3000)));
